# Generated by Django 4.1.7 on 2023-03-06 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminHome', '0005_alter_customer_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Position',
            new_name='position',
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='start_date',
            field=models.DateTimeField(verbose_name=datetime.datetime),
        ),
    ]
